### PR TITLE
[第5組]Refactor: Almost Re-Build full backend

### PR DESCRIPTION
**Pull request by ptchen314**
## Summary
Refactor the single file `main.py` into a modular architecture to improve maintainability and readability.

## Changes
1. Create a modular directory structure
2. Categorize related functionality into different modules
3. Implement dependency injection pattern
4. Optimize routing management
5. Standardize error handling

## Add file structure
```
src/
├── main.py
├── config.py
├── constants.py
├── database.py
├── dependencies.py
├── models.py
├── schemas.py
├── services.py
    ├── auth/
    |     ├── auth.py
    |     ├── config.py
    |     ├── dependencies.py
    |     ├── models.py
    |     ├── schemas.py
    |     └── services.py
    ├── news/
    |     ├── news.py
    |     ├── config.py
    |     ├── dependencies.py
    |     ├── models.py
    |     ├── schemas.py
    |     └── services.py
    └── prices/
          └── prices.py
```

### 1. add dependencies 
- Extract database connection and user authentication logic into separate dependencies
- Implement a unified error handling mechanism

### 2. Add routers/
- Categorize API routes by functionality
- auth.py: User authentication related APIs
- news.py: News related APIs
- prices.py: Prices related APIs

### 3. Add services.py
- Extract business logic into service layer
- Implement AuthService, NewsService, and AIService

### 4. Add database.py
- Centralize database connection settings
- Provide database session management mechanism

### 5. Add config.py
- Centralize all configuration items
- Support reading configuration from environment variables

## Notes
- This refactoring does not change any existing functionality
- Keep the original API interfaces unchanged
- Keep the original database structure
- Ensure downward compatibility

## Related documents
- API documentation remains unchanged
- Added documentation for the modular architecture
- Updated deployment guide

## Review points
1. Code organization structure
2. Error handling mechanism
3. Implementation of dependency injection
4. Configuration management approach
5. Code readability

## PT Notes
Please review this PR to ensure that the refactored code quality and maintainability are improved, while not affecting existing functionality.

And please use the Chinese(Traditional) to write the comment. Plz q.q
Oh and this PR was generated by claude-3-ops.

### CODE REVIEW

**Review by siangting — CHANGES_REQUESTED** [review]
Please modify your file structure.

**Comment by ptchen314** [comment]
fixed!

**Comment by taro0513** [comment]
LGTM!

**Comment by yozen0405** [comment]
這次重構的最大亮點在於清晰的模組結構，將主文件 main.py 的邏輯分拆到各個模組中，使得每個模組的責任明確，並依功能劃分 API 路由（如auth、news、prices）。這樣的分工讓代碼的擴展性變得更加靈活，便於後續增加新功能。將業務邏輯提取到 services.py 層並使用依賴注入的模式，這種設計使得功能測試更獨立，也能減少模組之間的耦合度。此外，統一的錯誤處理機制讓代碼在處理例外情況時更具一致性。但例如完全相同的 models, config 在重複出現在 根目錄, auth/, news/，可能不太好，建議進一步精簡並優化配置的集中管理（例如統一import自根目錄的 models, config）。

**Pull request merged**
